# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - master

env:
  REGISTRY: registry.hub.docker.com
  REGISTRY_USERNAME: x71c9
  IMAGE_NAME: uranio
  # GITLAB_PROJECT_ID: 38562332
  # IMAGE_NAME: ${{ github.repository }}

jobs:
  push_to_registry:
    name: Push Uranio Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Log in to Docker Registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_ACCESS_TOKEN }}

      - name: Configure SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.GH_PRIVATE_KEY }}

      # - name: Set outputs
      #   id: vars
      #   run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.REGISTRY_USERNAME }}/${{ env.IMAGE_NAME }}:latest

